### PR TITLE
use yay if installed to see package information

### PR DESCRIPTION
**Pull request by willydeliege**
## Summary by CodeRabbit

- **New Features**
	- Enhanced package management flexibility by allowing the use of the `yay` package manager as an alternative to `pacman` for retrieving package information.
	- Improved command execution based on the availability of the `yay` package manager.

### CODE REVIEW

**Comment by Freed-Wu** [comment]
Can you provide some detail about the difference between `yay -Si` and `pacman -Si`?

I use `paru` not `yay` :)

**Comment by willydeliege** [comment]
> Can you provide some detail about the difference between `yay -Si` and `pacman -Si`?
> 
> I use `paru` not `yay` :)

yay -Si shows information from aur's while pacman -Si shows informations only in packages found in the repositories configured in  pacman.conf..
➜ pacman -Si hyprland-git
error: package 'hyprland-git' was not found
➜ yay  -Si hyprland-git
Repository                    : aur
Name                          : hyprland-git
...

paru works exactiy like yay , so pacman.zsh source can be extended to paru as well

**Comment by Freed-Wu** [comment]
If hyprland-git only belongs AUR, `pacman -Si <Tab>` will not get the candidate and we don't need to preview it by yay. IMO.

**Comment by Freed-Wu** [comment]
screen-2024-08-30-14-50-38

Now it works. Thank you!

**Comment by willydeliege** [comment]
Thanks for merging

**Pull request merged**
