### PR TITLE
:bug: Fix #17, support darwin's ps

### LINKED ISSUE #17: kill completions dosen't work on macos
Screenshot 2024-04-15 at 11 41 16 AM

### PR DESCRIPTION
**Pull request by Freed-Wu**
## Summary by CodeRabbit

- **New Features**
	- Improved `ps` command compatibility across different operating systems by adding a conditional OS check.
	- Modified `ps` command to use `wocommand` instead of `wocmd.

### CODE REVIEW

**Comment by Magniquick** [comment]
Screenshot 2024-04-16 at 3 05 01 PM
Alas, how sad.

**Comment by Freed-Wu** [comment]
What is the output:

```sh
echo $OSTYPE
```

**Comment by Magniquick** [comment]
```
❯ echo $OSTYPE
darwin23.0
```
you probably want:
```
❯ uname -s
Darwin
```

**Comment by Freed-Wu** [comment]
Can you try current version? I believe it should work.

**Comment by Magniquick** [comment]
Screenshot 2024-04-16 at 4 10 33 PM

**Comment by Freed-Wu** [comment]
OK, can it work now?

**Comment by Magniquick** [comment]
Screenshot 2024-04-16 at 10 36 03 PM

**Comment by Freed-Wu** [comment]
OK, Can it work now?

**Comment by Magniquick** [comment]
Screenshot 2024-04-17 at 3 31 55 PM /
I suggest you install the bsd coreutils on your system and try your patches there - that would make this back and forth less necessary.

**Comment by Magniquick** [comment]
Screenshot 2024-04-17 at 3 34 17 PM
I suggest you install the bsd coreutils on your system and try your patches there - that would make this back and forth less necessary.

**Comment by Freed-Wu** [comment]
IMG20240417183521

It works.

**Comment by Magniquick** [comment]
Screenshot 2024-04-18 at 12 04 58 AM \
Maybe the tab completion is getting overwritten ? How would I check for that ?
Any other output you want ?

**Comment by Freed-Wu** [comment]
> Maybe the tab completion is getting overwritten

I doubt it is due to alias not work. Can you add `echo $aliases[--no-headers]` after `fi`?

**Comment by Magniquick** [comment]
It's empty !
What should I do to fix that ?

**Comment by Magniquick** [comment]
gives | tail -n1
(the script given in fzf-tab wiki actually works flawlessly for me, and also seems to include more processes -non child processes ?)
For reference:
```zsh
# give a preview of commandline arguments when completing `kill`
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-preview \
  '[[ $group == "[process ID]" ]] && ps --pid=$word -o cmd --no-headers -w -w'
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-flags --preview-window=down:3:wrap
```

**Pull request merged**
